export class INF_Survey_DiedAdd{
    public personId: string;
    public surveyId: string;
    public citizenId: string;
    public prefix: string;
    public firstName: string;
    public lastName: string;
    public fullName: string;
    public birthDate: string;
    public age: number;
    public dateDied: any;
    public causeCode: string;
    public causeName: string;
    public causeOtherCode: string;
    public causeOtherName: string;
    public placeCode: string;
    public placeOtherCode: string;
    public placeOtherName: string;
    public disease: string;
}