export class HospitalBean{
    public code5: string;
    public code9: string;
    public hospitalName: string;
    public hospitalTypeCode: string;
    public address: string;
    public tumbolCode: string;
    public amphurCode: string;
    public provinceCode: string;
    public mooNo: string;
    public telephone: string;
    public fax: string;
    public zipCode: string;
    public hospitalMasterCode: string;
    public contactPrefix: string;
    public contactFirstName: string;
    public contactLastName: string;
    public contactCitizenId: string;
    public contactTelephone: string;
    public contactEmail: string;
    public isActive: boolean;
    public isRegister: boolean;
}