import { } from "@angular/core";
export class PersonBean {
    public citizenId: string = "";
    public firstName: string = "";
    public lastName: string = "";
    public fullName: string = "";
    public nickName: string = "";
    public genderCode: string = "";
    public genderName: string = "";
    public prefixCode: string = "";
    public prefixName: string = "";
    public raceCode: string = "";
    public raceName: string = "";
    public nationalityCode: string = "";
    public nationalityName: string = "";
    public religionCode: string = "";
    public religionName: string = "";
    public bloodTypeId: string = "";
    public bloodTypeName: string = "";
    public rHGroupId: string = "";
    public rHGroupName: string = "";
    public birthDate: string = "";
    public educationCode: string = "";
    public educationName: string = "";
    public educationDescription: string = "";
    public occupationCode: string = "";
    public occupationName: string = "";
    public dischargeId: string = "";
    public familyStatus: string = "";
    public guest: boolean = false;
    public age;

    public fatherCID: string = "";
    public montherCID: string = "";
    public cupleCID: string = "";
    public typeAreaCode: string = "";
    public vStatusCode: string = "";
    public laborCode: string = "";
    public passport: string = "";
    public isDead: boolean;
    public deadDate: boolean;
    public healthInsurananceType: string = "";
    public ageYear: string = "";
    public ageMonth: string = "";
    public homeNo: string = "";
    public villageNo: string = "";
    public tumbolName: string = "";
    public amphurName: string = "";
    public provinceName: string = "";
    public osmId;
    public latitude : string ="";
    public longitude : string = "";

}