export class PersonalBasicBean{
    public personId: string;
    public citizenId: string;
    public firstName: string;
    public lastName: string;
    public fullName: string;
    public birthDate: string;
    public prefixCode: string;
    public prefixName: string;
    public genderId: string;
    public genderName: string;
    public hospitalCode5: string;
    public address: string;
    public homeId: string;
    public homeNo: string;
    public villageId: string;
    public villageNo: string;
    public tumpolCode: string;
    public tumpolName: string;
    public amphurCode: string;
    public amphurName: string;
    public provinceCode: string;
    public provinceName: string;
    public zipcode: string;
    public osmId: string;
    public roleId: string;
    public active: boolean;
    
}