export class PregnantBean{
    public citizenId: string = "";
    public firstName: string = "";
    public lastName: string = "";
    public fullName: string = "";
    public nickName: string = "";
    public genderCode: string = "";
    public genderName: string = "";
    public prefixCode: string = "";
    public prefixName: string = "";
    public raceCode: string = "";
    public raceName: string = "";
    public nationalityCode: string = "";
    public nationalityName: string = "";
    public religionCode: string = "";
    public religionName: string = "";
    public bloodTypeId: string = "";
    public bloodTypeName: string = "";
    public rHGroupId: string = "";
    public rHGroupName: string = "";
    public birthDate: any;
    public educationCode: string = "";
    public educationName: string = "";
    public educationDescription: string = "";
    public occupationCode: string = "";
    public occupationName: string = "";
    public dischargeId: string = "";
    public familyStatus: string = "";
    public age: number;
    public address : string;
}